### ISSUE TITLE
Slow generating...

### ISSUE THREAD

**Issue by 440459012** [marcbachmann/node-html-pdf#326]
how fast must be generated the pdf, in my app it take about 5 seconds, is it normal, or maybe i made a mistake in my code...?

`renderedHTML = ejs.render(html, { data:data})
          res.type('pdf')
          res.attachment(req.params[0] + '.pdf')
          pdf.create(renderedHTML, options).toBuffer(function (err, buffer) {
            if (err) {
              res.sendStatus(400)
            }
            res.end(buffer, 'binary')
          })`

**Comment by marcbachmann** [comment]
There was a process exit close issue. It's fixed in v2.2.0.
Can you please try that version. Reopen if it's still too slow for you.

This module forks a new process every time, so there's a small overhead, but most times this is acceptable for generating a pdf. Depending on the size of your pdf, phantomjs can get really slow.
I guess the performance of chrome would be better.

I don't like to invest too much time on this module as I don't expect much development from the phantomjs core team anymore.

**Comment by sdeshpande4** [comment]
I still face an issue. Creating a 680-page pdf takes around 95 seconds.

**Comment by Pensarfeo** [comment]
+1; it also takes around 6 seconds for the pdf to be created. I am using toBuffer!

**Comment by thomashummer** [comment]
I'm on version 2.2.0
it takes about 6 seconds to stream: (single A4-page)
pdf.create(html).toStream((err, stream) => {
                      if (err) return res.end(err.stack);
                      res.setHeader('Content-Type', 'application/pdf');
                      stream.pipe(res);

**Comment by syarhei** [comment]
Do anyone find a solution to resolve it?
